### ISSUE TITLE
Implement relative positioning for commands

### ISSUE THREAD

**Issue by Nul-led** [ABCxFF/diepcustom#122]
Preferably using "~" as a replacement due to minecraft already using this, aka increasing familiarity :p

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
wdym

**Comment by Nul-led** [comment]
like summoning an entity at x: ~, y: ~ would summon it at the players location, or x: ~-4, but 4 to the left etc etc
