### ISSUE TITLE
Inaccuracy of Guardian boss move speed

### ISSUE THREAD

**Issue by PowfuArras** [ABCxFF/diepcustom#18]
**What is inconsistent**
The guardian boss feels like it is moving way faster than what it should, as of now it moves faster than a tank with 5 points of speed

**Expected behavior**
Move much slower

**Screenshots**

**Additional notes**
Could possibly have been correct at one point, but then the drone spawner started applying recoil later in development making it move faster (This also could be completely wrong and instead it could just have a higher base move speed than it should and not being affected by recoil)

**Comment by CoderSudaWuda** [comment]
This seems realistic, the Fallen Overlord and many other bosses also have inconsistencies. I'm filing an issue about the Fallen Overlord later.

**Comment by ABCxFF** [comment]
Will focus on this and other boss inconsistencies in future. Not top priority yet, though thanks for reporting!

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
has been fixed a while ago
