### ISSUE TITLE
auto barrels do not reward score on kill

### ISSUE THREAD

**Issue by Craabby** [ABCxFF/diepcustom#19]
**What is inconsistent**
auto barrels do you reward score when you kill stuff with them

**Expected behavior**
they should give the score

**Comment by CoderSudaWuda** [comment]
What a tragic inconsistency overlooked by ABC.

**Comment by ABCxFF** [comment]
https://github.com/ABCxFF/diepcustom/commit/c92d5171745b6b172135d85e1922c11167285bcb. May be reopened in the future depending on if this commit is kept
