### ISSUE TITLE
Constant `OUTPUT_BUFFER` capacity can cause crashes

### ISSUE THREAD

**Issue by ABCxFF** [ABCxFF/diepcustom#2]
Once compressor is built (waiting on #1), deal with this maximum output buffer capacity.

https://github.com/ABCxFF/diepcustom/blob/main/src/Coder/Writer.ts#L25

As of now, server crashes if u see enough objects be made at once (only happens when on high FOV so it doesn't matter much anyway).

**Comment by Nul-led** [comment]
possible quick fix might be to split large fovs/packets into two.. idk if the client accepts 2 0x00 packets with the same tick
