### ISSUE TITLE
Dev Password Vulnerability

### ISSUE THREAD

**Issue by Altanis** [ABCxFF/diepcustom#27]
**Describe the bug**
Considering if the project is forked onto Repl.it and Glitch, it would most likely be open source, so the dev password would be public.

**Screenshots**
If applicable, add screenshots to help explain your findings.

**Additional notes**
Remove the default of `config.devPasswordHash`.

**Comment by ABCxFF** [comment]
Will probably make instead the default hash == to sha256(""), so that everyone has developer - almost as a feature - unless modified.
