### ISSUE TITLE
Arena Closers body does not take damage (animation)

### ISSUE THREAD

**Issue by n0deee** [ABCxFF/diepcustom#30]
**What is inconsistent**
Don't do the damage animation after taking damage

**Expected behavior**
Plays the damage animation when takes damage

**Additional notes**
<em>I know arena closers are immortal just to be clear</em>
Another thing to notice is that in the arena closer code he has 10000 hp and hides his health bar. As there is no godmode in diepcustom, setting the health to Infinity and not hiding the health bar can be a solution

**Comment by n0deee** [comment]
Note that I'm talking about the boss/legit arena closer, not the arena closer tank

**Comment by Nul-led** [comment]
Alternatively we could make invincibility a thing :p
Wouldnt be that crazy of an idea and can be further used by anyone who wants to

**Comment by ABCxFF** [comment]
Thank you for reporting the issue! Will fix this within the next day. Reiterating what we discussed in discord.

> This line which sets `damageReduction` to `0`, makes the AC immortal. This is how its likely done in actual diep - since in actual diep, ACs have 10k health, yet take no damage.
https://github.com/ABCxFF/diepcustom/blob/main/src/Entity/Misc/ArenaCloser.ts#L66
