### ISSUE TITLE
Take control of neutral dominators

### ISSUE THREAD

**Issue by Altanis** [ABCxFF/diepcustom#34]
**What is inconsistent**
You can take control of neutral dominators.

**Expected behavior**
Only dominators on your team are able to be taken control of.

**Screenshots**
![image](https://user-images.githubusercontent.com/38045884/195719667-9902b0f6-10f4-4e0c-84eb-2df818c7730a.png)

**Comment by ABCxFF** [comment]
If you tested this on localhost on the newest version, you probably defaulted to FullAccess aka devmode, since the password is default to `""`. In which case, this would be by design. Could you confirm your client's `accessLevel` != 3 during testing?

**Comment by Altanis** [comment]
oh yeah i had dev mode enabled, whoops; ill try it with dev mode disabled

**Comment by Altanis** [comment]
yes my mistake, ill close this issue
