### ISSUE TITLE
Inaccuracy

### ISSUE THREAD

**Issue by murchalkin** [ABCxFF/diepcustom#35]
Aim bosses is wrong.

**Comment by Nul-led** [comment]
Known inaccuracy i think :)
Dunno if / when we re gonna fix it

**Comment by n0deee** [comment]
could you provide more details?

**What exactly is happening?**
**What should be the expected behavior?**
If possible, **screenshots or videos** would help

**Comment by murchalkin** [comment]
this aim wrong. on all bosses

**Comment by murchalkin** [comment]
you can check on localhost

**Comment by murchalkin** [comment]
or on my private server

**Comment by ABCxFF** [comment]
Bosses AIs and boss stats are going to be fixed in the future

**Comment by murchalkin** [comment]
thanks
