### ISSUE TITLE
Spectator gets attacked by AIs

### ISSUE THREAD

**Issue by Nul-led** [ABCxFF/diepcustom#44]
**What is inconsistent**
The spectator has no tankbody so it shouldnt be attacked by eg. crashers

**Comment by Nul-led** [comment]
(only happens when ai is already focused on target)

**Comment by Nul-led** [comment]
![image](https://user-images.githubusercontent.com/63370961/198709018-78b5b546-72aa-477e-8150-34ce0de34437.png)

**Comment by Altanis** [comment]
I'll make a PR to fix this
