### ISSUE TITLE
Spectator Healthbar Shows

### ISSUE THREAD

**Issue by Altanis** [ABCxFF/diepcustom#49]
**What is inconsistent**
The healthbar of someone using the spectator tank is visible.

**Expected behavior**
A spectator should not have a healthbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/38045884/199279971-87ffbd7a-4745-4669-88e3-bedfd202e2f7.png)

**Comment by ABCxFF** [comment]
Further, the spectator shouldn't be sent to the client at all.
