### ISSUE TITLE
Dominator can be on fallen team

### ISSUE THREAD

**Issue by Altanis** [ABCxFF/diepcustom#50]
**What is inconsistent**
Dominator goes onto fallen team if killed by fallen member.

**Expected behavior**
Dominator should remain neutral.

**Screenshots**
https://youtu.be/SOnHLG-4CyQ

**Additional notes**
Add any other context about the inconsistency here.

**Comment by n0deee** [comment]
Video in timing: https://youtu.be/SOnHLG-4CyQ?t=144 (2:24)
