### ISSUE TITLE
Changelog text (cstr) does not support cyrillic symbols

### ISSUE THREAD

**Issue by murchalkin** [ABCxFF/diepcustom#51]

**Comment by Nul-led** [comment]
> @Nul-led use `new TextEncoder().encode(changelog)` instead of `...changelog` to get its bytes. Currently, I'm afraid it doesn't support any non-ASCII character, not just cyrillic.

Yea cstr uses TextEncoder under the hood. The encoder should be able to encode / the decoder should be able to decode any utf8 non ascii chars and since the result produced (in the discord report) even resulted in nonascii chars, the issue may be somewhere else..

**Comment by ABCxFF** [comment]
Issue was in the text encoding of served content
