### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by iIDragonterrorIi** [ABCxFF/diepcustom#52]
For some reason, anyone can push K for levels. How do i fix this? This probalbly also applies to ; for god and o to kill.

**Comment by murchalkin** [comment]
dev token

**Comment by n0deee** [comment]
currently diepcustom is like this, I don't think it's an issue.
anyway if you need help with this you can join our discord and go to chat #support

**Comment by iIDragonterrorIi** [comment]
ok, thanks for the answers! Where would i find the Dev Token? And could i remove those commands entirly?

**Comment by n0deee** [comment]
To set a password for the developer, you need to set the environment variable DEV_PASSWORD_HASH to a SHA256 hash of the desired password (you can find "converters" on the internet).

To use the password, you must set the `password` variable in localstorage to the clear (non-hashed) password. you can do this using the command `localStorage.password = "examplePassword";` in the devtools console (remember to replace `examplePassword` to your password)

**Comment by Nul-led** [comment]
Issue seems to be solved..
