### ISSUE TITLE
Camera FOV upon death is inaccurate

### ISSUE THREAD

**Issue by Altanis** [ABCxFF/diepcustom#58]
**What is inconsistent**
When dying to another player, the client's FOV is set to 0.4.

**Expected behavior**
The client's FOV should be set to the same FOV as their killer.

**Comment by Nul-led** [comment]
wrong, 0.4 is infact the correct value, try 2 tanks one suicides into a ranger at level 0 or smth to make it more obvious, you will see that the fov of the ranger is much larger than the fov that the dead player sees
