### ISSUE TITLE
Spike tank icon moves weirdly away from the leaderboard

### ISSUE THREAD

**Issue by supahero1** [ABCxFF/diepcustom#62]
![image](https://user-images.githubusercontent.com/47268949/202207505-1fabff0e-e6e7-462d-9dac-bd03e3c40a09.png)

Replicate: just spawn in (fresh tab) and kill a square/move (moving by itself sometimes works, if it doesn't then kill a square). It's displayed alright when you don't move and you just spawn, but once you move it just goes 360 noscope tokyo drift away from its proper position.

**Comment by ABCxFF** [comment]
Bug in m28's client. Unsure if we'll attempt to fix, but either way going to close for now since it's not part of the version we are providing in this repo.
