### ISSUE TITLE
Bases do not act like proper walls - high health projectiles can go through

### ISSUE THREAD

**Issue by CoderSudaWuda** [ABCxFF/diepcustom#7]
Players inside their base can take damage.

**Comment by CoderSudaWuda** [comment]
Tanks do, drones don't

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
thats how it is in original diep.io, but seems to be more apparent here

**Comment by CoderSudaWuda** [comment]
> thats how it is in original diep.io, but seems to be more apparent here

It's an unintended feature in diep

**Comment by BlueCannonBall** [comment]
> > thats how it is in original diep.io, but seems to be more apparent here
> 
> It's an unintended feature in diep

Definitely not true. It's very very easy to make them instantly kill on contact. The decision not to do this is clearly intentional.
