### ISSUE TITLE
Necro Drones constructor without abstract shape

### ISSUE THREAD

**Issue by ABCxFF** [ABCxFF/diepcustom#73]
Let there be a way to initialize necro drones without an abstract shape. @c86ec23b-fef1-4979-b2fa-b9adc351b8cc, this also will help simplify summoner in the future as well.

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
summoner in diep is 90% likely to be just a normal drone with 4 sides

**Comment by ABCxFF** [comment]
#88
