### ISSUE TITLE
Allow for initialization of projectile/NecromancerSquare without AbstractShape reference

### ISSUE THREAD

**Issue by ABCxFF** [ABCxFF/diepcustom#88]
```ts
export default class NecromancerSquare extends Drone {
    public constructor(barrel: Barrel, tank: BarrelBase, tankDefinition: TankDefinition | null, shootAngle: number, shape: AbstractShape) {

```
this is preventing people from using necro drones as a bullet type - since they *require* a shape parameter.

**Comment by Nul-led** [comment]
Can't we just expose a seperate method setShape and use the default square in the ctor?

**Comment by ABCxFF** [comment]
That'd be fine too - could also use like a static method `NecromancerSquare.fromShape()` - either or : shrug:

**Comment by Nul-led** [comment]
yea fromShape is easier access, let's do that
